import subprocess
from datetime import datetime
from pathlib import Path
from config import CV_TAILORED_PATH, OUTPUT_DIR

def compile_cv(job):
    # Extract Company name and generate a dynamic filename
    company = job["company"].replace(" ", "_")
    date = datetime.now().strftime("%Y-%m-%d")
    pdf_name = "CV_Nesrine_" + company + "_" + date + ".pdf"
    # Build the LaTeX compilation command (pdflatex)
    command = [
        "pdflatex",
        "-interaction=nonstopmode",
        "-output-directory=" + str(OUTPUT_DIR),
        str(CV_TAILORED_PATH)
    ]
    #Execute the LaTeX compilation process
    try:
        subprocess.run(command, check=True)
    except Exception as e:
        print("Erreur compilation:", e)
        return None
    # Define the default output PDF generated by LaTeX
    old_path = OUTPUT_DIR / "main_tailored_IA_version.pdf"
    # Rename the generated PDF to a custom name (company + date)
    new_path = OUTPUT_DIR / pdf_name
    old_path.rename(new_path)
    # Delete temporary files
    for extension in [".aux", ".log", ".out"]:
    temp_file = OUTPUT_DIR / ("main_tailored_IA_version" + extension)
    if temp_file.exists():
        temp_file.unlink()
    # Return the final PDF path 
    return new_path